### ISSUE TITLE
Can't define map file path

### ISSUE THREAD

**Issue by buep** [Praqma/memory-map-plugin#26]
Originally filed as Jenkins CI Jira issue https://issues.jenkins-ci.org/browse/JENKINS-32424
We only use GHI now.

[Christian Opitz](https://issues.jenkins-ci.org/secure/ViewProfile.jspa?name=chrop) wrote:

---

No matter in which format I add the file name, I either get an error message or the file is not found.
Jenkins ver. 1.625.3 on Windows 7

__Examples:__

No files found
Error message: Filematcher found no files using pattern X in folder Y
Not found patterns (including the quotation marks):
"_bin*.map"
"C:\Projekte\myproject\ _bin*.map"
"_bin\XXX-XXX100_000300_R1931_20160113_0854.map"

Exception
_bin\XXX-XXX100_000300_R1931_20160113_0854.map
_bin\ *.map
*.map

What is interesting, is that the error message says that there was an exception for input string "g" (marked in bold below) although, there is no "g" in the input string...

```
Memory Map Plugin version 2.1.2 (cfc34)
ERROR: Build step failed with exception
java.lang.NumberFormatException: For input string: "g"
at java.lang.NumberFormatException.forInputString(Unknown Source)
at java.lang.Long.parseLong(Unknown Source)
at net.praqma.jenkins.memorymap.util.HexUtils$HexifiableString.getLongValue(HexUtils.java:81)
at net.praqma.jenkins.memorymap.parser.gcc.GccMemoryMapParser$MemoryMapMemItemComparator.compare(GccMemoryMapParser.java:124)
at net.praqma.jenkins.memorymap.parser.gcc.GccMemoryMapParser$MemoryMapMemItemComparator.compare(GccMemoryMapParser.java:120)
at java.util.TimSort.binarySort(Unknown Source)
at java.util.TimSort.sort(Unknown Source)
at java.util.TimSort.sort(Unknown Source)
at java.util.Arrays.sort(Unknown Source)
at java.util.Collections.sort(Unknown Source)
at net.praqma.jenkins.memorymap.parser.gcc.GccMemoryMapParser.guessLengthOfSections(GccMemoryMapParser.java:139)
at net.praqma.jenkins.memorymap.parser.gcc.GccMemoryMapParser.parseMapFile(GccMemoryMapParser.java:168)
at net.praqma.jenkins.memorymap.parser.MemoryMapMapParserDelegate.invoke(MemoryMapMapParserDelegate.java:61)
at net.praqma.jenkins.memorymap.parser.MemoryMapMapParserDelegate.invoke(MemoryMapMapParserDelegate.java:39)
at hudson.FilePath.act(FilePath.java:991)
at hudson.FilePath.act(FilePath.java:969)
at net.praqma.jenkins.memorymap.MemoryMapRecorder.perform(MemoryMapRecorder.java:161)
at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
at hudson.model.Build$BuildExecution.post2(Build.java:185)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
at hudson.model.Run.execute(Run.java:1766)
at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
at hudson.model.ResourceController.execute(ResourceController.java:98)
at hudson.model.Executor.run(Executor.java:408)
Build step 'Memory Map Publisher' marked build as failure
```

**Comment by buep** [comment]
The conclusions on [JENKINS-32424](https://issues.jenkins-ci.org/browse/JENKINS-32424) narrows down to there should be a better error message when file can't be parsed.

Further the that reason for not being able to parse them is because of the Tricore-Gcc compiler output in another format that the usual GCC compiler.
