### ISSUE TITLE
Memory map plugin fails when Linker Command FIle is not UTF-8 (Texas Instruments)

### ISSUE THREAD

**Issue by buep** [Praqma/memory-map-plugin#32]
Originally filed as https://issues.jenkins-ci.org/browse/JENKINS-28259 but we use Github issues now.

Reported by Florian Reinhard which also supplied a patch.

## Steps to reproduce:

* use a Linker command file that contains umlauts like öäü
* save it as with this encoding: cp1252
* run a build with jenkins
* now you'll see that jenkins will fail, because it opens the command file as utf-8 and will fail to decode the umlauts

## Background:

Texas Instruments C6000 Code generation tools Version 6.1.x can't even use utf-8 encoded linker command files, the linker will fail.

## Possible solutions:

* add some magic to determine the command file encoding
* let the user define the encoding
* use the systems default encoding ( java:Charset.defaultCharset() )
* try utf-8 and ascii (attached patch, low quality, just as a idea)

**Comment by mjfwest** [comment]
is this the expected symptom of this bug?  Is there a resolution?
```
Aug 21, 2019 6:46:05 PM FINE class net.praqma.jenkins.memorymap.parser.AbstractMemoryMapParser
Parser M3_parser created input stream for file.
Aug 21, 2019 6:46:05 PM FINE class net.praqma.jenkins.memorymap.parser.AbstractMemoryMapParser
Parser M3_parser closed input stream for file.
Aug 21, 2019 6:46:05 PM FINE class net.praqma.jenkins.memorymap.parser.AbstractMemoryMapParser
Parser C28xx_parser created input stream for file.
Aug 21, 2019 6:46:05 PM FINE class net.praqma.jenkins.memorymap.parser.AbstractMemoryMapParser
Parser C28xx_parser reported exception of type IOException.
Aug 21, 2019 6:46:05 PM FINE class net.praqma.jenkins.memorymap.parser.AbstractMemoryMapParser
Parser C28xx_parser closed input stream for file.
Aug 21, 2019 6:46:05 PM SEVERE net.praqma.jenkins.memorymap.MemoryMapRecorder perform
Abnormal plugin execution, trace written to log
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(Unknown Source)
	at java.nio.charset.CharsetDecoder.decode(Unknown Source)
	at net.praqma.jenkins.memorymap.parser.AbstractMemoryMapParser.createCharSequenceFromFile(AbstractMemoryMapParser.java:144)
	at net.praqma.jenkins.memorymap.parser.AbstractMemoryMapParser.createCharSequenceFromFile(AbstractMemoryMapParser.java:128)
	at net.praqma.jenkins.memorymap.parser.ti.TexasInstrumentsMemoryMapParser.parseConfigFile(TexasInstrumentsMemoryMapParser.java:89)
	at net.praqma.jenkins.memorymap.parser.MemoryMapConfigFileParserDelegate.invoke(MemoryMapConfigFileParserDelegate.java:58)
	at net.praqma.jenkins.memorymap.parser.MemoryMapConfigFileParserDelegate.invoke(MemoryMapConfigFileParserDelegate.java:41)
	at hudson.FilePath.act(FilePath.java:1076)
	at hudson.FilePath.act(FilePath.java:1059)
	at net.praqma.jenkins.memorymap.MemoryMapRecorder.perform(MemoryMapRecorder.java:89)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
